name: crafty_bay
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  widget_and_text_animator: ^1.1.5
  pin_code_fields: ^8.0.1
  device_preview: ^1.2.0
  get: ^4.6.6
  http: ^1.2.2
  floating_snackbar: ^1.0.5
  shared_preferences: ^2.3.1
  jwt_decoder: ^2.0.1
  flutter_carousel_widget: ^2.3.0
  cached_network_image: ^3.4.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg


  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf

     - family: Poppins Medium
       fonts:
         - asset: assets/fonts/Poppins-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
